---
name: Update CLI Docs

on:
  pull_request:

jobs:
  docs:
    name: Update Docs
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Source
        uses: actions/checkout@v3

      # Go Build
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.2"

      - name: Go Build
        run: "go build ./cmd/monzo"

      # Generate Docs
      - name: Generate Docs
        run: "./monzo generate-docs ./cmd/monzo/docs/"

      - name: Push Updated Docs
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: updating cli docs"
          files: ./cmd/monzo/docs/
